server:
  port: 6001

spring:
  application:
    name: microservice-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: microservice-zuul6001     #自定义服务名称信息
    prefer-ip-address: true                        #访问路径可以显示IP地址
zuul:
  prefix: /MySubSystemNameProvider
  ignored-services: microservicecloud-provider
  routes:
    mydept.serviceId: microservicecloud-provider
    mydept.path: /provider/**

info:
  app.name: microservice-zuul
  company.name: www.lc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
