server:
  port: 7000
spring:
  application:
    name: eurka-server
  #security:
    #user:
      #name: lc
      #password: 1
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


