spring:
 datasource:
 ###################以下为druid增加的配置###########################
      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
#      username: test
#      password: 1
      url: ENC(r6r78I/rdbZfaderiuJGTFIlvsDavgEcejIlMJvL/RHcXvCw8wANBL/bxOnrTaZBnDSsI3arJ9gVE6yRE/JWWGYeprL0ysff+wNvHzfxN0CFQ7XPJnpXiA==)
      username: ENC(SJqCvdidQCJ8QHtSPI53Qw==)
      password: ENC(nRQiCK8EM2uSDutsF304yA==)
      driverClassName: com.mysql.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      ###############以上为配置druid添加的配置########################################
# thymeleaf
 thymeleaf:
       cache: false
       prefix: classpath:/templates/
       suffix: .html
       encoding: UTF-8
       content-type: text/html
       mode: HTML5
jpa:
       properties:
       hibernate:
       database: MySQL
       show_sql: true
       format_sql: true
       database-platform: org.hibernate.dialect.MySQL5Dialect

mybatis:
  #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
  map-underscore-to-camel-case: true
  #mybatis的mapper文件所在路径
  mapper-locations: classpath:mapper/*.xml
  #实体类路径
  type-aliases-package: com.lc.entity

logging:
  level:
    org.springframework.security: INFO
    com.lc.mapper: debug

#jasypt加密的密匙
jasypt:
    encryptor:
      password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
#服务器端口号
server:
     port: 8888
#rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回

